name: FACECONTROL Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to KPI server
        uses: appleboy/ssh-action@v1
        with:
          host: 192.168.0.199
          username: akbarali
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/FACECONTROL
            ./deploy.sh
